global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'transaction-validator'
    static_configs:
      - targets: ['app_blue:3000', 'app_green:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
